// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: v1alpha1/user.proto

package v1alpha1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserSource defines the source of user
type UserSource int32

const (
	UserSource_USER_SOURCE_UNSPECIFIED UserSource = 0
	UserSource_USER_SOURCE_LOCAL       UserSource = 1
)

// Enum value maps for UserSource.
var (
	UserSource_name = map[int32]string{
		0: "USER_SOURCE_UNSPECIFIED",
		1: "USER_SOURCE_LOCAL",
	}
	UserSource_value = map[string]int32{
		"USER_SOURCE_UNSPECIFIED": 0,
		"USER_SOURCE_LOCAL":       1,
	}
)

func (x UserSource) Enum() *UserSource {
	p := new(UserSource)
	*p = x
	return p
}

func (x UserSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserSource) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_user_proto_enumTypes[0].Descriptor()
}

func (UserSource) Type() protoreflect.EnumType {
	return &file_v1alpha1_user_proto_enumTypes[0]
}

func (x UserSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserSource.Descriptor instead.
func (UserSource) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_user_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	Source        UserSource             `protobuf:"varint,5,opt,name=source,proto3,enum=matrixhub.v1alpha1.UserSource" json:"source,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_v1alpha1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_v1alpha1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *User) GetSource() UserSource {
	if x != nil {
		return x.Source
	}
	return UserSource_USER_SOURCE_UNSPECIFIED
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_v1alpha1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_v1alpha1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_user_proto_rawDescGZIP(), []int{2}
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_v1alpha1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_user_proto_rawDescGZIP(), []int{3}
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_v1alpha1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_user_proto_rawDescGZIP(), []int{4}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_v1alpha1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	Source        UserSource             `protobuf:"varint,5,opt,name=source,proto3,enum=matrixhub.v1alpha1.UserSource" json:"source,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_v1alpha1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *GetUserResponse) GetSource() UserSource {
	if x != nil {
		return x.Source
	}
	return UserSource_USER_SOURCE_UNSPECIFIED
}

func (x *GetUserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_v1alpha1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_user_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUserRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_v1alpha1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_user_proto_rawDescGZIP(), []int{8}
}

type SetUserSysAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SysadminFlag  bool                   `protobuf:"varint,2,opt,name=sysadmin_flag,json=sysadminFlag,proto3" json:"sysadmin_flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserSysAdminRequest) Reset() {
	*x = SetUserSysAdminRequest{}
	mi := &file_v1alpha1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserSysAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserSysAdminRequest) ProtoMessage() {}

func (x *SetUserSysAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserSysAdminRequest.ProtoReflect.Descriptor instead.
func (*SetUserSysAdminRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_user_proto_rawDescGZIP(), []int{9}
}

func (x *SetUserSysAdminRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetUserSysAdminRequest) GetSysadminFlag() bool {
	if x != nil {
		return x.SysadminFlag
	}
	return false
}

type SetUserSysAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserSysAdminResponse) Reset() {
	*x = SetUserSysAdminResponse{}
	mi := &file_v1alpha1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserSysAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserSysAdminResponse) ProtoMessage() {}

func (x *SetUserSysAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserSysAdminResponse.ProtoReflect.Descriptor instead.
func (*SetUserSysAdminResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_user_proto_rawDescGZIP(), []int{10}
}

type ResetUserPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetUserPasswordRequest) Reset() {
	*x = ResetUserPasswordRequest{}
	mi := &file_v1alpha1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUserPasswordRequest) ProtoMessage() {}

func (x *ResetUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_user_proto_rawDescGZIP(), []int{11}
}

func (x *ResetUserPasswordRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResetUserPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResetUserPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetUserPasswordResponse) Reset() {
	*x = ResetUserPasswordResponse{}
	mi := &file_v1alpha1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetUserPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUserPasswordResponse) ProtoMessage() {}

func (x *ResetUserPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUserPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetUserPasswordResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_user_proto_rawDescGZIP(), []int{12}
}

var File_v1alpha1_user_proto protoreflect.FileDescriptor

const file_v1alpha1_user_proto_rawDesc = "" +
	"\n" +
	"\x13v1alpha1/user.proto\x12\x12matrixhub.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x14v1alpha1/utils.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x19\n" +
	"\bis_admin\x18\x04 \x01(\bR\aisAdmin\x126\n" +
	"\x06source\x18\x05 \x01(\x0e2\x1e.matrixhub.v1alpha1.UserSourceR\x06source\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"x\n" +
	"\x11CreateUserRequest\x12#\n" +
	"\busername\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\busername\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bpassword\x12\x19\n" +
	"\bis_admin\x18\x03 \x01(\bR\aisAdmin\"\x14\n" +
	"\x12CreateUserResponse\"d\n" +
	"\x10ListUsersRequest\x12\x1b\n" +
	"\x04page\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x83\x01\n" +
	"\x11ListUsersResponse\x12.\n" +
	"\x05users\x18\x01 \x03(\v2\x18.matrixhub.v1alpha1.UserR\x05users\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.matrixhub.v1alpha1.PaginationR\n" +
	"pagination\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\"\xe1\x01\n" +
	"\x0fGetUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x19\n" +
	"\bis_admin\x18\x04 \x01(\bR\aisAdmin\x126\n" +
	"\x06source\x18\x05 \x01(\x0e2\x1e.matrixhub.v1alpha1.UserSourceR\x06source\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\"\x14\n" +
	"\x12DeleteUserResponse\"V\n" +
	"\x16SetUserSysAdminRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\x12#\n" +
	"\rsysadmin_flag\x18\x02 \x01(\bR\fsysadminFlag\"\x19\n" +
	"\x17SetUserSysAdminResponse\"X\n" +
	"\x18ResetUserPasswordRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bpassword\"\x1b\n" +
	"\x19ResetUserPasswordResponse*@\n" +
	"\n" +
	"UserSource\x12\x1b\n" +
	"\x17USER_SOURCE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11USER_SOURCE_LOCAL\x10\x012\xb3\x06\n" +
	"\x05Users\x12u\n" +
	"\tListUsers\x12$.matrixhub.v1alpha1.ListUsersRequest\x1a%.matrixhub.v1alpha1.ListUsersResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1alpha1/users\x12{\n" +
	"\n" +
	"CreateUser\x12%.matrixhub.v1alpha1.CreateUserRequest\x1a&.matrixhub.v1alpha1.CreateUserResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1alpha1/users\x12t\n" +
	"\aGetUser\x12\".matrixhub.v1alpha1.GetUserRequest\x1a#.matrixhub.v1alpha1.GetUserResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1alpha1/users/{id}\x12}\n" +
	"\n" +
	"DeleteUser\x12%.matrixhub.v1alpha1.DeleteUserRequest\x1a&.matrixhub.v1alpha1.DeleteUserResponse\" \x82\xd3\xe4\x93\x02\x1a*\x18/api/v1alpha1/users/{id}\x12\xa4\x01\n" +
	"\x11ResetUserPassword\x12,.matrixhub.v1alpha1.ResetUserPasswordRequest\x1a-.matrixhub.v1alpha1.ResetUserPasswordResponse\"2\x82\xd3\xe4\x93\x02,:\x01*\"'/api/v1alpha1/users/{id}/reset-password\x12\x99\x01\n" +
	"\x0fSetUserSysAdmin\x12*.matrixhub.v1alpha1.SetUserSysAdminRequest\x1a+.matrixhub.v1alpha1.SetUserSysAdminResponse\"-\x82\xd3\xe4\x93\x02':\x01*\x1a\"/apis/v1alpha1/users/{id}/sysadminB<Z:github.com/matrixhub-ai/matrixhub/api/go/v1alpha1;v1alpha1b\x06proto3"

var (
	file_v1alpha1_user_proto_rawDescOnce sync.Once
	file_v1alpha1_user_proto_rawDescData []byte
)

func file_v1alpha1_user_proto_rawDescGZIP() []byte {
	file_v1alpha1_user_proto_rawDescOnce.Do(func() {
		file_v1alpha1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1alpha1_user_proto_rawDesc), len(file_v1alpha1_user_proto_rawDesc)))
	})
	return file_v1alpha1_user_proto_rawDescData
}

var file_v1alpha1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1alpha1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_v1alpha1_user_proto_goTypes = []any{
	(UserSource)(0),                   // 0: matrixhub.v1alpha1.UserSource
	(*User)(nil),                      // 1: matrixhub.v1alpha1.User
	(*CreateUserRequest)(nil),         // 2: matrixhub.v1alpha1.CreateUserRequest
	(*CreateUserResponse)(nil),        // 3: matrixhub.v1alpha1.CreateUserResponse
	(*ListUsersRequest)(nil),          // 4: matrixhub.v1alpha1.ListUsersRequest
	(*ListUsersResponse)(nil),         // 5: matrixhub.v1alpha1.ListUsersResponse
	(*GetUserRequest)(nil),            // 6: matrixhub.v1alpha1.GetUserRequest
	(*GetUserResponse)(nil),           // 7: matrixhub.v1alpha1.GetUserResponse
	(*DeleteUserRequest)(nil),         // 8: matrixhub.v1alpha1.DeleteUserRequest
	(*DeleteUserResponse)(nil),        // 9: matrixhub.v1alpha1.DeleteUserResponse
	(*SetUserSysAdminRequest)(nil),    // 10: matrixhub.v1alpha1.SetUserSysAdminRequest
	(*SetUserSysAdminResponse)(nil),   // 11: matrixhub.v1alpha1.SetUserSysAdminResponse
	(*ResetUserPasswordRequest)(nil),  // 12: matrixhub.v1alpha1.ResetUserPasswordRequest
	(*ResetUserPasswordResponse)(nil), // 13: matrixhub.v1alpha1.ResetUserPasswordResponse
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
	(*Pagination)(nil),                // 15: matrixhub.v1alpha1.Pagination
}
var file_v1alpha1_user_proto_depIdxs = []int32{
	0,  // 0: matrixhub.v1alpha1.User.source:type_name -> matrixhub.v1alpha1.UserSource
	14, // 1: matrixhub.v1alpha1.User.created_at:type_name -> google.protobuf.Timestamp
	1,  // 2: matrixhub.v1alpha1.ListUsersResponse.users:type_name -> matrixhub.v1alpha1.User
	15, // 3: matrixhub.v1alpha1.ListUsersResponse.pagination:type_name -> matrixhub.v1alpha1.Pagination
	0,  // 4: matrixhub.v1alpha1.GetUserResponse.source:type_name -> matrixhub.v1alpha1.UserSource
	14, // 5: matrixhub.v1alpha1.GetUserResponse.created_at:type_name -> google.protobuf.Timestamp
	4,  // 6: matrixhub.v1alpha1.Users.ListUsers:input_type -> matrixhub.v1alpha1.ListUsersRequest
	2,  // 7: matrixhub.v1alpha1.Users.CreateUser:input_type -> matrixhub.v1alpha1.CreateUserRequest
	6,  // 8: matrixhub.v1alpha1.Users.GetUser:input_type -> matrixhub.v1alpha1.GetUserRequest
	8,  // 9: matrixhub.v1alpha1.Users.DeleteUser:input_type -> matrixhub.v1alpha1.DeleteUserRequest
	12, // 10: matrixhub.v1alpha1.Users.ResetUserPassword:input_type -> matrixhub.v1alpha1.ResetUserPasswordRequest
	10, // 11: matrixhub.v1alpha1.Users.SetUserSysAdmin:input_type -> matrixhub.v1alpha1.SetUserSysAdminRequest
	5,  // 12: matrixhub.v1alpha1.Users.ListUsers:output_type -> matrixhub.v1alpha1.ListUsersResponse
	3,  // 13: matrixhub.v1alpha1.Users.CreateUser:output_type -> matrixhub.v1alpha1.CreateUserResponse
	7,  // 14: matrixhub.v1alpha1.Users.GetUser:output_type -> matrixhub.v1alpha1.GetUserResponse
	9,  // 15: matrixhub.v1alpha1.Users.DeleteUser:output_type -> matrixhub.v1alpha1.DeleteUserResponse
	13, // 16: matrixhub.v1alpha1.Users.ResetUserPassword:output_type -> matrixhub.v1alpha1.ResetUserPasswordResponse
	11, // 17: matrixhub.v1alpha1.Users.SetUserSysAdmin:output_type -> matrixhub.v1alpha1.SetUserSysAdminResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_v1alpha1_user_proto_init() }
func file_v1alpha1_user_proto_init() {
	if File_v1alpha1_user_proto != nil {
		return
	}
	file_v1alpha1_utils_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1alpha1_user_proto_rawDesc), len(file_v1alpha1_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1alpha1_user_proto_goTypes,
		DependencyIndexes: file_v1alpha1_user_proto_depIdxs,
		EnumInfos:         file_v1alpha1_user_proto_enumTypes,
		MessageInfos:      file_v1alpha1_user_proto_msgTypes,
	}.Build()
	File_v1alpha1_user_proto = out.File
	file_v1alpha1_user_proto_goTypes = nil
	file_v1alpha1_user_proto_depIdxs = nil
}
